---
sidebar: sidebar 
permalink: vcp_task_create_manage_user_accounts.html 
summary: È possibile creare e gestire account utente utilizzando il plug-in. 
keywords: netapp, storage, accounts, vcp, vcenter, element 
---
= Creare e gestire gli account utente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:vcp_concept_accounts.html["Account utente"] Vengono utilizzati per controllare l'accesso alle risorse di storage su una rete basata su software NetApp Element.

.Opzioni
* <<Creare un account>>
* <<Modificare un account>>
* <<Eliminare un account>>




== Creare un account

È possibile creare un account utente univoco per consentire l'accesso ai volumi di storage.

.Di cosa hai bisogno
* È necessario aggiungere ed eseguire almeno un cluster.


.Fasi
. In vSphere Web Client, aprire la scheda *Gestione*:
+
** A partire dal plug-in Element vCenter 5.0, selezionare *plug-in remoto NetApp Element > Gestione > Gestione*.
** Per il plug-in Element vCenter 4.10 e versioni precedenti, selezionare *Gestione NetApp Element > Gestione*.


+

NOTE: Se vengono aggiunti due o più cluster, assicurarsi che il cluster che si intende utilizzare per l'attività sia selezionato nella barra di navigazione.

. Selezionare la sottoscheda *account*.
. Selezionare *Crea account*.
. Immettere un nome utente.
+

TIP: Utilizzare le Best practice di denominazione descrittive. Ciò è particolarmente importante se nell'ambiente vengono utilizzati più cluster o server vCenter.

. Nella sezione *Impostazioni CHAP*:
+
.. Immettere il segreto dell'iniziatore per l'autenticazione della sessione del nodo CHAP.
.. Inserire il segreto di destinazione per l'autenticazione della sessione del nodo CHAP.
+

NOTE: I segreti dell'iniziatore e di destinazione devono essere diversi. Se questi campi vengono lasciati vuoti, il sistema genera le credenziali di autenticazione.



. Fare clic su *OK* per creare l'account.




== Modificare un account

È possibile modificare un account utente per modificare lo stato o i segreti CHAP. La modifica delle impostazioni CHAP può causare la perdita di connettività tra un host e i volumi associati.

.A proposito di questa attività
Se si utilizzano volumi persistenti con il nodo di gestione, non modificare il nome account dell'account associato a questi volumi.

.Fasi
. In vSphere Web Client, aprire la scheda *Gestione*:
+
** A partire dal plug-in Element vCenter 5.0, selezionare *plug-in remoto NetApp Element > Gestione > Gestione*.
** Per il plug-in Element vCenter 4.10 e versioni precedenti, selezionare *Gestione NetApp Element > Gestione*.


+

NOTE: Se vengono aggiunti due o più cluster, assicurarsi che il cluster che si intende utilizzare per l'attività sia selezionato nella barra di navigazione.

. Selezionare la sottoscheda *account*.
. Selezionare la casella di controllo dell'account che si desidera modificare.
. Selezionare *azioni*.
. Nel menu visualizzato, selezionare *Edit* (Modifica).
. Se necessario, modificare quanto segue:
+
.. Consente di modificare lo stato di accesso dell'account.
+

IMPORTANT: La modifica dell'accesso a *Locked* termina tutte le connessioni iSCSI all'account e l'account non è più accessibile. I volumi associati all'account vengono mantenuti; tuttavia, i volumi non sono rilevabili con iSCSI.

.. Modificare le credenziali segrete dell'iniziatore o di destinazione utilizzate per l'autenticazione della sessione del nodo.
+

NOTE: Se non si modificano le credenziali, queste rimangono invariate. Se i campi delle credenziali vengono vuoti, il sistema genera nuove password.



. Fare clic su *OK*.




== Eliminare un account

È possibile eliminare gli account utente utilizzando il punto di estensione del plug-in.

.Di cosa hai bisogno
Eliminare e rimuovere i volumi associati all'account o riassegnare i volumi a un altro account.


IMPORTANT: Se si utilizzano volumi persistenti con il nodo di gestione, non eliminare l'account associato a questi volumi.

.Fasi
. In vSphere Web Client, aprire la scheda *Gestione*:
+
** A partire dal plug-in Element vCenter 5.0, selezionare *plug-in remoto NetApp Element > Gestione > Gestione*.
** Per il plug-in Element vCenter 4.10 e versioni precedenti, selezionare *Gestione NetApp Element > Gestione*.


+

NOTE: Se vengono aggiunti due o più cluster, assicurarsi che il cluster che si intende utilizzare per l'attività sia selezionato nella barra di navigazione.

. Selezionare la sottoscheda *account*.
. Selezionare la casella di controllo dell'account che si desidera eliminare.
. Fare clic su *azioni*.
. Nel menu visualizzato, selezionare *Delete* (Elimina).
. Confermare l'azione.




== Trova ulteriori informazioni

* https://docs.netapp.com/us-en/hci/index.html["Documentazione NetApp HCI"^]
* https://www.netapp.com/data-storage/solidfire/documentation["Pagina SolidFire and Element Resources"^]

